const { Opportunity } = require("./models");

const SEED = [
  { title: "Software Engineering Intern", company: "Google", type: "internship", location: "Bangalore, IN", deadline: "2026-04-15", stipend: "₹1,20,000/mo", difficulty: "Advanced", duration: "12 weeks", description: "Work on Google Search infrastructure with world-class engineers. Contribute to production systems used by billions.", required_skills: ["Python","Data Structures","Algorithms","C++"], eligibility: ["Pre-final year","CGPA 8+","CS/IT background"], tags: ["FAANG","Tech","Backend"], logo: "🔍" },
  { title: "STEP Intern", company: "Google", type: "internship", location: "Remote", deadline: "2026-03-30", stipend: "₹80,000/mo", difficulty: "Intermediate", duration: "14 weeks", description: "First and second-year students with technical skills join Google to grow their coding and leadership abilities.", required_skills: ["Java","Python","JavaScript","Git"], eligibility: ["1st or 2nd year","No prior internship required"], tags: ["Beginner-Friendly","Diversity"], logo: "🎯" },
  { title: "Software Development Engineer Intern", company: "Amazon", type: "internship", location: "Hyderabad, IN", deadline: "2026-05-01", stipend: "₹1,10,000/mo", difficulty: "Advanced", duration: "16 weeks", description: "Build scalable services on AWS. Work on real customer problems with global impact.", required_skills: ["Java","AWS","System Design","SQL"], eligibility: ["Pre-final year","Strong DSA"], tags: ["Cloud","FAANG"], logo: "📦" },
  { title: "Full-Stack Developer Intern", company: "Razorpay", type: "internship", location: "Bangalore, IN", deadline: "2026-04-20", stipend: "₹75,000/mo", difficulty: "Intermediate", duration: "6 months", description: "Build fintech products used by millions of merchants. Ship real features from day one.", required_skills: ["React","Node.js","MongoDB","REST APIs"], eligibility: ["Final year","Portfolio required"], tags: ["Fintech","Startup"], logo: "💳" },
  { title: "ML Research Intern", company: "Microsoft Research", type: "internship", location: "Bangalore, IN", deadline: "2026-04-10", stipend: "₹1,50,000/mo", difficulty: "Advanced", duration: "12 weeks", description: "Publish papers with MSR India. Work on cutting-edge ML problems.", required_skills: ["Python","PyTorch","Deep Learning","Research"], eligibility: ["Masters/PhD preferred","Publications a plus"], tags: ["Research","AI/ML"], logo: "🧪" },
  { title: "Product Design Intern", company: "Zomato", type: "internship", location: "Gurgaon, IN", deadline: "2026-03-25", stipend: "₹50,000/mo", difficulty: "Intermediate", duration: "6 months", description: "Design experiences for 100M+ users. Own end-to-end product flows.", required_skills: ["Figma","UI/UX","User Research","Prototyping"], eligibility: ["Any year","Portfolio required"], tags: ["Design","Consumer"], logo: "🎨" },
  { title: "Frontend Engineering Intern", company: "Meta", type: "internship", location: "Remote", deadline: "2026-05-10", stipend: "$8000/mo", difficulty: "Advanced", duration: "12 weeks", description: "Build React features for Facebook and Instagram web experiences.", required_skills: ["React","JavaScript","TypeScript","CSS"], eligibility: ["Pre-final/Final year","Open source contributions"], tags: ["FAANG","Frontend"], logo: "🌐" },
  { title: "Data Science Intern", company: "Swiggy", type: "internship", location: "Bangalore, IN", deadline: "2026-04-05", stipend: "₹70,000/mo", difficulty: "Intermediate", duration: "6 months", description: "Solve delivery optimization and demand forecasting problems.", required_skills: ["Python","SQL","Statistics","Pandas"], eligibility: ["Any year","ML coursework"], tags: ["Data","Analytics"], logo: "🛵" },
  { title: "Cybersecurity Intern", company: "CRED", type: "internship", location: "Bangalore, IN", deadline: "2026-04-25", stipend: "₹80,000/mo", difficulty: "Advanced", duration: "4 months", description: "Protect financial data of premium users. Work on threat detection and pentesting.", required_skills: ["Security","Networking","Linux","Python"], eligibility: ["Final year","Security certifications a plus"], tags: ["Security","Fintech"], logo: "🔐" },
  { title: "DevOps Engineering Intern", company: "Atlassian", type: "internship", location: "Remote", deadline: "2026-05-15", stipend: "₹90,000/mo", difficulty: "Intermediate", duration: "6 months", description: "Automate deployment pipelines for Jira and Confluence.", required_skills: ["Docker","Kubernetes","AWS","CI/CD"], eligibility: ["Pre-final/Final year"], tags: ["DevOps","Cloud"], logo: "⚙️" },
  { title: "Growth Marketing Intern", company: "Notion", type: "internship", location: "Remote", deadline: "2026-03-20", stipend: "$3000/mo", difficulty: "Beginner", duration: "3 months", description: "Drive user growth through content, community, and campaigns.", required_skills: ["Content Writing","Analytics","SEO","Social Media"], eligibility: ["Any year"], tags: ["Marketing","Growth"], logo: "📈" },
  { title: "iOS Developer Intern", company: "Apple", type: "internship", location: "Bangalore, IN", deadline: "2026-04-30", stipend: "₹1,30,000/mo", difficulty: "Advanced", duration: "12 weeks", description: "Build features for iOS apps used by millions.", required_skills: ["Swift","iOS SDK","UIKit","SwiftUI"], eligibility: ["Pre-final year","iOS portfolio"], tags: ["Mobile","FAANG"], logo: "🍎" },
  { title: "Smart India Hackathon 2026", company: "Government of India", type: "hackathon", location: "Pan-India", deadline: "2026-03-15", stipend: "₹1,00,000 prize", difficulty: "Intermediate", duration: "36 hours", description: "Nation's biggest hackathon. Solve real problems from ministries and PSUs.", required_skills: ["Full-Stack","Problem Solving","Teamwork"], eligibility: ["Any UG/PG student","Team of 6"], tags: ["National","Impact"], logo: "🇮🇳" },
  { title: "HackMIT 2026", company: "MIT", type: "hackathon", location: "Cambridge, MA", deadline: "2026-06-01", stipend: "$20,000 prize", difficulty: "Advanced", duration: "48 hours", description: "One of the world's most prestigious student hackathons.", required_skills: ["Any programming","Innovation"], eligibility: ["Any student worldwide"], tags: ["Global","Prestigious"], logo: "🎓" },
  { title: "Ethereum Global Hackathon", company: "ETHGlobal", type: "hackathon", location: "Online", deadline: "2026-04-08", stipend: "$50,000 prize pool", difficulty: "Advanced", duration: "72 hours", description: "Build the future of Web3 with top mentors and sponsors.", required_skills: ["Solidity","Web3","Blockchain","JavaScript"], eligibility: ["Any developer"], tags: ["Web3","Crypto"], logo: "⛓️" },
  { title: "Devfolio Hacktoberfest", company: "Devfolio", type: "hackathon", location: "Online", deadline: "2026-03-28", stipend: "₹5,00,000 prize pool", difficulty: "Intermediate", duration: "1 week", description: "India's leading open-source and product hackathon.", required_skills: ["Web Dev","Mobile","Open Source"], eligibility: ["Any developer"], tags: ["Open Source","Community"], logo: "🎃" },
  { title: "NASA Space Apps Challenge", company: "NASA", type: "hackathon", location: "Global", deadline: "2026-05-20", stipend: "Trip to NASA HQ", difficulty: "Intermediate", duration: "48 hours", description: "Use NASA data to solve challenges on Earth and in space.", required_skills: ["Data Science","Creativity","Any tech"], eligibility: ["All ages","All skill levels"], tags: ["Space","Global"], logo: "🚀" },
  { title: "AI4Good Hackathon", company: "Google + UN", type: "hackathon", location: "Online", deadline: "2026-04-12", stipend: "$25,000 prize", difficulty: "Intermediate", duration: "1 month", description: "Build AI solutions for UN Sustainable Development Goals.", required_skills: ["ML","Python","Social Impact"], eligibility: ["Students & professionals"], tags: ["AI","Impact"], logo: "🌍" },
  { title: "TechCrunch Disrupt Hackathon", company: "TechCrunch", type: "hackathon", location: "San Francisco", deadline: "2026-05-25", stipend: "$10,000 + investor meetings", difficulty: "Advanced", duration: "24 hours", description: "Compete alongside startups at TechCrunch Disrupt.", required_skills: ["Full-Stack","Product","Pitching"], eligibility: ["18+","Global"], tags: ["Startup","Prestigious"], logo: "🏆" },
  { title: "Google Generation Scholarship", company: "Google", type: "scholarship", location: "India", deadline: "2026-04-10", stipend: "₹1,00,000", difficulty: "Intermediate", description: "For students committed to diversity in tech. Includes mentorship and Google summit.", required_skills: ["Academic Excellence","Leadership"], eligibility: ["Women in CS","Undergrad"], tags: ["Diversity","Prestigious"], logo: "🏅" },
  { title: "Reliance Foundation Undergrad Scholarship", company: "Reliance Foundation", type: "scholarship", location: "India", deadline: "2026-03-31", stipend: "₹2,00,000/year", difficulty: "Beginner", description: "Merit and means-based scholarship for undergraduates across streams.", required_skills: ["Academic Merit"], eligibility: ["1st year","Family income < ₹15L"], tags: ["Need-Based","Merit"], logo: "💎" },
  { title: "INSPIRE Scholarship", company: "Dept. of Science & Tech, GoI", type: "scholarship", location: "India", deadline: "2026-04-30", stipend: "₹80,000/year", difficulty: "Beginner", description: "For top-ranked science students pursuing UG/PG in natural/basic sciences.", required_skills: ["Science Aptitude"], eligibility: ["Top 1% in 12th boards","Pursuing science"], tags: ["Government","Science"], logo: "🔬" },
  { title: "Adobe India Women-in-Tech Scholarship", company: "Adobe", type: "scholarship", location: "India", deadline: "2026-04-15", stipend: "$1,000 + internship", difficulty: "Intermediate", description: "Empowering women in computing with financial support and Adobe internship.", required_skills: ["Programming","Innovation"], eligibility: ["Women in CS","Undergrad"], tags: ["Diversity","Tech"], logo: "🎓" },
  { title: "OpenAI Residency Scholarship", company: "OpenAI", type: "scholarship", location: "Remote", deadline: "2026-05-15", stipend: "$40,000 stipend", difficulty: "Advanced", description: "6-month residency for exceptional individuals transitioning into AI research.", required_skills: ["Python","ML","Research","Math"], eligibility: ["Any background","Strong portfolio"], tags: ["AI","Research"], logo: "🤖" },
  { title: "MITACS Globalink Research Fellowship", company: "MITACS Canada", type: "fellowship", location: "Canada", deadline: "2026-04-01", stipend: "CAD 8,000 + travel", difficulty: "Advanced", duration: "12 weeks", description: "Research internship at top Canadian universities.", required_skills: ["Research","Domain Expertise"], eligibility: ["3rd/4th year UG","CGPA 8+"], tags: ["Research","International"], logo: "🍁" },
  { title: "Kleiner Perkins Fellowship", company: "Kleiner Perkins", type: "fellowship", location: "San Francisco", deadline: "2026-04-20", stipend: "Top-of-market", difficulty: "Advanced", duration: "12 weeks", description: "Join a top KP portfolio startup with cohort mentorship from partners.", required_skills: ["Engineering/Product/Design","High Agency"], eligibility: ["Undergraduate","US work eligibility"], tags: ["Startup","Prestigious"], logo: "🏆" },
  { title: "Rhodes Scholarship", company: "Rhodes Trust", type: "fellowship", location: "Oxford, UK", deadline: "2026-07-31", stipend: "Full tuition + £18,000/year", difficulty: "Advanced", duration: "2 years", description: "One of the world's most prestigious graduate scholarships.", required_skills: ["Academic Excellence","Leadership","Service"], eligibility: ["Under 24","Bachelor's degree"], tags: ["Global","Elite"], logo: "🎖️" },
  { title: "Y Combinator Startup School", company: "Y Combinator", type: "fellowship", location: "Online", deadline: "2026-03-30", stipend: "Access to YC network", difficulty: "Intermediate", duration: "10 weeks", description: "Free online program for aspiring founders with weekly group sessions.", required_skills: ["Entrepreneurship","Product","Hustle"], eligibility: ["Anyone with a startup idea"], tags: ["Entrepreneurship","Global"], logo: "🧡" },
  { title: "ACM ICPC World Finals", company: "ACM", type: "competition", location: "Various", deadline: "2026-04-20", stipend: "Global recognition", difficulty: "Advanced", description: "World's most prestigious competitive programming contest.", required_skills: ["Algorithms","DSA","Team problem-solving"], eligibility: ["Team of 3","Under 25"], tags: ["CP","Prestigious"], logo: "💻" },
  { title: "Google Code Jam", company: "Google", type: "competition", location: "Online", deadline: "2026-04-05", stipend: "$15,000 first prize", difficulty: "Advanced", description: "Annual algorithmic programming contest by Google.", required_skills: ["Algorithms","Any language"], eligibility: ["18+","Global"], tags: ["CP","Google"], logo: "🏅" },
  { title: "Kaggle Grandmaster Competition", company: "Kaggle", type: "competition", location: "Online", deadline: "2026-05-01", stipend: "$100,000 prize pool", difficulty: "Advanced", description: "ML competition on real-world datasets from top companies.", required_skills: ["ML","Python","Feature Engineering"], eligibility: ["Anyone"], tags: ["ML","Data"], logo: "📊" },
  { title: "Microsoft Imagine Cup", company: "Microsoft", type: "competition", location: "Global", deadline: "2026-04-25", stipend: "$100,000 + Azure credits", difficulty: "Intermediate", description: "Global student startup competition using Microsoft tech.", required_skills: ["Full-Stack","Azure","Innovation"], eligibility: ["Students 16+","Team of up to 4"], tags: ["Startup","Microsoft"], logo: "🏆" },
  { title: "MIT UROP", company: "MIT", type: "research", location: "Cambridge, MA", deadline: "2026-05-01", stipend: "$8,000 + housing", difficulty: "Advanced", duration: "10 weeks", description: "Undergraduate Research Opportunities Program at MIT labs.", required_skills: ["Research","Domain Fundamentals"], eligibility: ["Junior/Senior UG"], tags: ["Research","Elite"], logo: "🏛️" },
  { title: "IIT Bombay Summer Research", company: "IIT Bombay", type: "research", location: "Mumbai, IN", deadline: "2026-03-31", stipend: "₹15,000/mo + accommodation", difficulty: "Intermediate", duration: "8 weeks", description: "Work with top faculty on cutting-edge research projects.", required_skills: ["Research aptitude","Coursework"], eligibility: ["Pre-final year UG","CGPA 8+"], tags: ["Research","National"], logo: "🇮🇳" },
  { title: "DAAD-WISE Fellowship", company: "DAAD Germany", type: "research", location: "Germany", deadline: "2026-04-30", stipend: "€861/mo + travel", difficulty: "Advanced", duration: "2-3 months", description: "Working Internships in Science and Engineering at German universities.", required_skills: ["Research","English fluency"], eligibility: ["3rd/4th year UG","STEM"], tags: ["Research","International"], logo: "🇩🇪" },
];

async function seedOpportunities() {
  const count = await Opportunity.countDocuments();
  if (count > 0) return count;
  await Opportunity.insertMany(SEED);
  return SEED.length;
}

module.exports = { seedOpportunities };
